// <auto-generated />
using System;
using DungeonsAndDragons.Battle.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DungeonsAndDragons.Battle.Migrations
{
    [DbContext(typeof(MonstersDbContext))]
    partial class MonstersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DungeounsAndDragons.Domain.Models.Monster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("AttackModifier")
                        .HasColumnType("integer");

                    b.Property<int>("AttackPerRound")
                        .HasColumnType("integer");

                    b.Property<int>("DamageCubeCost")
                        .HasColumnType("integer");

                    b.Property<int>("DamageCubesNumber")
                        .HasColumnType("integer");

                    b.Property<int>("DamageModifier")
                        .HasColumnType("integer");

                    b.Property<int>("HealthPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Monsters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0274631e-f105-42c0-ae95-857957f94565"),
                            ArmorClass = 12,
                            AttackModifier = 0,
                            AttackPerRound = 10,
                            DamageCubeCost = 8,
                            DamageCubesNumber = 7,
                            DamageModifier = 4,
                            HealthPoints = 100,
                            Name = "Asharra"
                        },
                        new
                        {
                            Id = new Guid("c784cfcd-9d38-4207-83bf-1fe0e11f0526"),
                            ArmorClass = 19,
                            AttackModifier = 6,
                            AttackPerRound = 23,
                            DamageCubeCost = 12,
                            DamageCubesNumber = 17,
                            DamageModifier = 85,
                            HealthPoints = 200,
                            Name = "Adult black dragon"
                        },
                        new
                        {
                            Id = new Guid("3581e7f6-f453-4799-b59f-c784ca3d2156"),
                            ArmorClass = 7,
                            AttackModifier = 2,
                            AttackPerRound = 10,
                            DamageCubeCost = 8,
                            DamageCubesNumber = 3,
                            DamageModifier = 0,
                            HealthPoints = 40,
                            Name = "Lemure"
                        },
                        new
                        {
                            Id = new Guid("5249c3b4-6afa-4c95-b5a7-702402a7688c"),
                            ArmorClass = 10,
                            AttackModifier = -3,
                            AttackPerRound = 4,
                            DamageCubeCost = 4,
                            DamageCubesNumber = 1,
                            DamageModifier = 1,
                            HealthPoints = 15,
                            Name = "Badger"
                        },
                        new
                        {
                            Id = new Guid("b1c58c88-b3c7-4ade-a3d4-df8e6da449f4"),
                            ArmorClass = 10,
                            AttackModifier = 0,
                            AttackPerRound = 10,
                            DamageCubeCost = 8,
                            DamageCubesNumber = 2,
                            DamageModifier = 0,
                            HealthPoints = 70,
                            Name = "Devil Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
